site_name: Einconv
site_url: https://example.com # TODO Fill in the link from the hosting platform
repo_url: https://github.com/f-dangel/einconv/
repo_name: f-dangel/einconv
site_author: Felix Dangel
nav:
    - Getting Started: index.md
    - Tutorials:
          - Basic Example (2d Convolution): tutorials/basic_conv2d.md
    - API documentation:
        - Modules: api/modules.md
        - Functionals: api/functionals.md
        - Einsum Expressions: api/expressions.md
        - Symbolic Simplifications: api/simplifications.md
        - Miscellaneous: api/miscellaneous.md
    - Developer notes: develop.md
theme:
    name: material
    logo: logo.png
    features:
        - content.code.copy
copyright: Copyright &copy; 2023 Felix Dangel
markdown_extensions:
    - pymdownx.arithmatex: # LaTeX math
          generic: true
    - pymdownx.highlight: # code highlighting
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite # code highlighting
    - pymdownx.snippets # code highlighting
    - pymdownx.superfences # code highlighting
plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                      show_root_heading: true
                      show_source: true
                      show_bases: false
                      show_signature_annotations: true
                      separate_signature: true
                      docstring_section_style: list
                      merge_init_into_class: true
extra_javascript:
    - javascripts/mathjax.js # LaTeX math
    - https://polyfill.io/v3/polyfill.min.js?features=es6 # LaTeX math
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # LaTeX math
