name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - development
      - master
      - main
      - release


jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make install-test
    - name: Run test
      if: contains('refs/heads/master refs/heads/main refs/heads/development refs/heads/release', github.ref)
      run: |
        make test
    - name: Run test-light
      if: contains('refs/heads/master refs/heads/main refs/heads/development refs/heads/release', github.ref) != 1
      run: |
        make test-light
